name: eagle_eye_app
description: A Flutter app for the Agentic AI Hackathon

publish_to: 'none' # prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.17.4
  #firebase_auth_web: ^5.6.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.4
  http: ^1.1.0
  speech_to_text: ^6.6.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
