// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSlBFuYegWWA2xFfCN2R-g7dVTGQ_sOA',
    appId: '1:576331613433:web:04def5ae5b1c0826f9ce28',
    messagingSenderId: '576331613433',
    projectId: 'project-drishti-eagle-eye',
    authDomain: 'project-drishti-eagle-eye.firebaseapp.com',
    storageBucket: 'project-drishti-eagle-eye.firebasestorage.app',
    measurementId: 'G-RSDDPMSQLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-hpDG8s802kW7RksIGygjyRRib4IJCGU',
    appId: '1:576331613433:android:455ac7275a1bbe44f9ce28',
    messagingSenderId: '576331613433',
    projectId: 'project-drishti-eagle-eye',
    storageBucket: 'project-drishti-eagle-eye.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ6dN9G59Rw4eqDpcSZSEiTffnZMPfxcI',
    appId: '1:576331613433:ios:83b8ad45fd9d3554f9ce28',
    messagingSenderId: '576331613433',
    projectId: 'project-drishti-eagle-eye',
    storageBucket: 'project-drishti-eagle-eye.firebasestorage.app',
    iosBundleId: 'com.example.agenticAiHackathonEagleEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ6dN9G59Rw4eqDpcSZSEiTffnZMPfxcI',
    appId: '1:576331613433:ios:83b8ad45fd9d3554f9ce28',
    messagingSenderId: '576331613433',
    projectId: 'project-drishti-eagle-eye',
    storageBucket: 'project-drishti-eagle-eye.firebasestorage.app',
    iosBundleId: 'com.example.agenticAiHackathonEagleEye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJSlBFuYegWWA2xFfCN2R-g7dVTGQ_sOA',
    appId: '1:576331613433:web:7d6fbcd44f1703a6f9ce28',
    messagingSenderId: '576331613433',
    projectId: 'project-drishti-eagle-eye',
    authDomain: 'project-drishti-eagle-eye.firebaseapp.com',
    storageBucket: 'project-drishti-eagle-eye.firebasestorage.app',
    measurementId: 'G-1LTX128YY9',
  );
}
